- name: disable old nodejs and enable nodejs
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs 
    state: present

# you dont need this if doing through CICD
# - name: Install dependencies
#   ansible.builtin.command: npm install
#   args:
#     chdir: /app